services:
  mqtt:
    networks:
      default: {}
      standalone-runtime: {}

  device-agent:
    networks:
      default: {}
      standalone-runtime:
        aliases:
          - edge-device-agent

networks:
  standalone-runtime:
    external: true
    name: ${STANDALONE_RUNTIME_NETWORK:-nexolab-standalone-runtime}
