per_listener_settings false

persistence true
persistence_location /mosquitto/data/
autosave_interval 30

log_dest stdout
log_timestamp true
connection_messages true

listener 8883 0.0.0.0
protocol mqtt
allow_anonymous false
allow_zero_length_clientid false
certfile /run/tls/server/mqtt-server.pem
keyfile /run/tls/server/mqtt-server.key
tls_version tlsv1.2

plugin /usr/local/lib/nexolab/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic-security.json

max_packet_size 1048576
max_queued_messages 10000
max_inflight_messages 100
persistent_client_expiration 14d

user mosquitto
