# NEXOLAB host reliability evidence.
# Override Raspberry Pi OS volatile journald storage so unexpected resets remain diagnosable.
[Journal]
Storage=persistent
Compress=yes
SystemMaxUse=256M
SystemKeepFree=2G
MaxRetentionSec=14day
SyncIntervalSec=1m
